#debug: true
server:
  port: 15001

management:
  security:
    enabled: false

logging:
  level:
    org.springframework.security: INFO

security:
  basic:
    enabled: false
  user:
    password: user
  oauth2:
    client:
      clientId: sg80UAGilC1dHw
      clientSecret: sHvh7PMnbom1eIk8aOv5qg
    resource:
      serviceId: ${PREFIX:}resource
      tokenInfoUri: http://localhost:9080/oidc/oauth2/introspect
