#debug: true
server:
  port: 15001

management:
  security:
    enabled: false

logging:
  level:
    org.springframework.security: INFO

security:
  basic:
    enabled: false
  user:
    password: user
  oauth2:
    client:
      clientId: eAcGkScqUy6u0g
      clientSecret: Q8TBeg6hO9zHZAsJ4A7loA
    resource:
      serviceId: ${PREFIX:}resource
      tokenInfoUri: http://iam.com:9080/oidc/oauth2/introspect
